# Generated by Django 5.0.6 on 2025-01-25 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ornamental', 'Ornamental'), ('frutal', 'Frutal'), ('aromaticas', 'Aromáticas'), ('hortalizas', 'Hortalizas')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='viveros/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
