# Generated by Django 5.0.6 on 2025-02-04 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ornamental', 'Ornamental'), ('frutal', 'Frutal'), ('aromaticas', 'Aromáticas'), ('hortalizas', 'Hortalizas')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='viveros/')),
                ('espacio_requerido', models.FloatField(help_text='Espacio requerido por la planta (por unidad) en m²')),
                ('consumo_agua', models.FloatField(help_text='Consumo de agua semanal en litros')),
                ('consumo_fertilizante', models.FloatField(help_text='Consumo de fertilizante mensual en gramos')),
                ('variedad', models.CharField(blank=True, choices=[('tomate', 'Tomate'), ('lechuga', 'Lechuga'), ('zanahoria', 'Zanahoria'), ('ejote', 'Ejote'), ('calabaza', 'Calabaza')], help_text='Seleccione la variedad o especie (por ejemplo, tomate)', max_length=50, null=True)),
                ('sistema_cultivo', models.CharField(blank=True, choices=[('hileras', 'Hileras'), ('surcos', 'Surcos'), ('tutorados', 'Tutorados'), ('mixto', 'Mixto')], help_text='Seleccione el sistema de cultivo a utilizar', max_length=50, null=True)),
                ('calidad_suelo', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Calidad del suelo para el cultivo', max_length=50, null=True)),
                ('sistema_riego', models.CharField(blank=True, choices=[('goteo', 'Goteo'), ('aspersión', 'Aspersión'), ('manual', 'Manual')], help_text='Método de riego que se aplicará', max_length=50, null=True)),
                ('tipo_poda', models.CharField(blank=True, choices=[('regular', 'Regular'), ('intensiva', 'Intensiva'), ('ninguna', 'Ninguna')], help_text='Tipo de poda que se aplicará al cultivo', max_length=50, null=True)),
                ('exposicion', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Nivel de exposición solar en el área de siembra', max_length=50, null=True)),
                ('area_sembrar', models.FloatField(blank=True, help_text='Área destinada para este cultivo en m² (dentro del total del vivero)', null=True)),
                ('tiempo_cultivo_estimado', models.IntegerField(default=120, help_text='Días estimados para que la planta esté lista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(help_text='Observación semanal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='vivero.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Vivero', max_length=255)),
                ('espacio_total', models.FloatField(help_text='Espacio total del vivero en m²')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vivero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='vivero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='vivero.vivero'),
        ),
    ]
