# Generated by Django 5.0.6 on 2025-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='area_sembrar',
            field=models.FloatField(blank=True, help_text='Área destinada para este cultivo en m² (dentro del total del vivero)', null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='calidad_suelo',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Calidad del suelo para el cultivo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='exposicion',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Nivel de exposición solar en el área de siembra', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='sistema_cultivo',
            field=models.CharField(blank=True, choices=[('hileras', 'Hileras'), ('surcos', 'Surcos'), ('tutorados', 'Tutorados'), ('mixto', 'Mixto')], help_text='Seleccione el sistema de cultivo a utilizar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='sistema_riego',
            field=models.CharField(blank=True, choices=[('goteo', 'Goteo'), ('aspersión', 'Aspersión'), ('manual', 'Manual')], help_text='Método de riego que se aplicará', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo_poda',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('intensiva', 'Intensiva'), ('ninguna', 'Ninguna')], help_text='Tipo de poda que se aplicará al cultivo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='variedad',
            field=models.CharField(blank=True, choices=[('tomate', 'Tomate'), ('lechuga', 'Lechuga'), ('zanahoria', 'Zanahoria'), ('ejote', 'Ejote'), ('calabaza', 'Calabaza')], help_text='Seleccione la variedad o especie (por ejemplo, tomate)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='espacio_requerido',
            field=models.FloatField(help_text='Espacio requerido por la planta (por unidad) en m²'),
        ),
    ]
