# Generated by Django 5.0.6 on 2025-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='tiempo_cultivo_estimado',
            new_name='dias_cosecha',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='observacion',
            field=models.TextField(help_text='Observaciones semanales'),
        ),
    ]
