# Generated by Django 5.0.6 on 2025-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0002_rename_tiempo_cultivo_estimado_planta_dias_cosecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='variedad',
            field=models.CharField(blank=True, choices=[('tomate', 'Tomate'), ('lechuga', 'Lechuga'), ('zanahoria', 'Zanahoria'), ('vainica', 'Vainica'), ('calabaza', 'Calabaza')], help_text='Seleccione la variedad o especie (por ejemplo, tomate)', max_length=50, null=True),
        ),
    ]
