# Generated by Django 5.0.6 on 2025-02-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0003_alter_planta_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='consumo_agua',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='consumo_fertilizante',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='espacio_requerido',
        ),
    ]
