# Generated by Django 5.0.6 on 2025-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0004_remove_planta_consumo_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='block_num',
            field=models.PositiveIntegerField(default=1, help_text='Número de bloque o sembradio donde se siembra esta planta'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='calidad_suelo',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='exposicion',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='sistema_cultivo',
            field=models.CharField(blank=True, choices=[('hileras', 'Hileras'), ('surcos', 'Surcos'), ('tutorados', 'Tutorados'), ('mixto', 'Mixto')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='sistema_riego',
            field=models.CharField(blank=True, choices=[('goteo', 'Goteo'), ('aspersión', 'Aspersión'), ('manual', 'Manual')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tipo_poda',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('intensiva', 'Intensiva'), ('ninguna', 'Ninguna')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='variedad',
            field=models.CharField(blank=True, choices=[('tomate', 'Tomate'), ('lechuga', 'Lechuga'), ('zanahoria', 'Zanahoria'), ('vainica', 'Vainica'), ('calabaza', 'Calabaza')], max_length=50, null=True),
        ),
    ]
