# Generated by Django 5.0.6 on 2025-02-19 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0005_planta_block_num_alter_planta_calidad_suelo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano_terreno', models.FloatField(help_text='Tamaño del terreno para cultivo en m²')),
                ('cantidad_sectores', models.PositiveIntegerField(help_text='Cantidad de sectores o sembradios')),
                ('topografia', models.CharField(choices=[('plano', 'Plano'), ('semiplano', 'Semiplano'), ('quebrado', 'Quebrado'), ('pendiente', 'Pendiente'), ('inclinado', 'Inclinado')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mapas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
