# Generated by Django 5.0.6 on 2025-02-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0006_mapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('insumos', 'Insumos'), ('almacenamiento', 'Almacenamiento'), ('herramientas', 'Herramientas'), ('varios', 'Varios')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano', models.FloatField(help_text='Tamaño de la bodega (en m²)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bodegas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
