# Generated by Django 5.0.6 on 2025-02-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0007_bodega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('tareas', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('salario', models.CharField(blank=True, max_length=50, null=True)),
                ('profesion', models.CharField(blank=True, max_length=255, null=True)),
                ('servicios_requeridos', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
