# Generated by Django 5.0.6 on 2025-02-21 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0008_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lista_productos', models.TextField(blank=True, null=True)),
                ('total_gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_transaccion', models.CharField(choices=[('gasto', 'Gasto'), ('venta', 'Venta'), ('mantenimiento', 'Mantenimiento'), ('equipo', 'Equipo'), ('inversion', 'Inversión'), ('planilla', 'Planilla'), ('servicios', 'Servicios'), ('insumos', 'Insumos')], max_length=50)),
                ('factura', models.ImageField(blank=True, null=True, upload_to='gastos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
