# Generated by Django 5.0.6 on 2025-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivero', '0009_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='total_gasto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
