# Generated by Django 5.0.6 on 2025-01-21 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('colones', 'Colones'), ('pesos', 'Pesos'), ('euros', 'Euros'), ('dolares', 'Dólares')], default='dolares', max_length=10)),
                ('categoria', models.CharField(choices=[('frutas_verduras', 'Frutas y Verduras'), ('ganado', 'Ganado'), ('propiedades', 'Propiedades'), ('vehiculos', 'Vehículos'), ('insumos', 'Insumos'), ('servicios', 'Servicios Profesionales')], max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_ganado', models.CharField(blank=True, choices=[('engorde', 'Engorde'), ('cria', 'Cría'), ('lechera', 'Lechera'), ('semental', 'Semental'), ('reproductivo', 'Reproductivo'), ('trabajo', 'Trabajo')], max_length=20, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genetica', models.CharField(blank=True, max_length=200, null=True)),
                ('pureza', models.CharField(blank=True, max_length=100, null=True)),
                ('razas_padres', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_areteo', models.CharField(blank=True, max_length=100, null=True)),
                ('actas_venta_nacimiento', models.ImageField(blank=True, null=True, upload_to='productos/actas/')),
                ('marca_propiedad', models.ImageField(blank=True, null=True, upload_to='productos/marca_propiedad/')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Marketplace.producto')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='productos/videos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Marketplace.producto')),
            ],
        ),
    ]
