# Generated by Django 5.0.6 on 2025-01-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_por_metro_cuadrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_propiedad',
            field=models.CharField(choices=[('finca', 'Finca'), ('quinta', 'Quinta'), ('lote', 'Lote'), ('Casa', 'Casa')], default='dolares', max_length=20),
        ),
    ]
