# Generated by Django 5.0.6 on 2025-01-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_producto_precio_por_metro_cuadrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
