# Generated by Django 5.0.6 on 2025-01-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0004_alter_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('pickub', 'Pickup'), ('camion', 'Camión'), ('trabajo', 'Trabajo')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo_de_propiedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_propiedad',
            field=models.CharField(choices=[('finca', 'Finca'), ('quinta', 'Quinta'), ('lote', 'Lote'), ('Casa', 'Casa')], default='finca', max_length=20),
        ),
    ]
