# Generated by Django 5.0.6 on 2025-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0005_producto_tipo_transmision_producto_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
