# Generated by Django 5.0.6 on 2025-01-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0006_producto_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('frutas_verduras', 'Frutas y Verduras'), ('animales', 'Animales'), ('ganado', 'Ganado'), ('propiedades', 'Propiedades'), ('vehiculos', 'Vehículos'), ('insumos', 'Insumos'), ('servicios', 'Servicios Profesionales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('finca', 'Finca'), ('quinta', 'Quinta'), ('lote', 'Lote'), ('Casa', 'Casa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_transmision',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('pickub', 'Pickup'), ('camion', 'Camión'), ('trabajo', 'Trabajo')], max_length=20, null=True),
        ),
    ]
