# Generated by Django 5.0.6 on 2025-01-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0007_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
