# Generated by Django 5.0.6 on 2025-01-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Biografía')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('actividad_comercial', models.CharField(choices=[('agropecuaria', 'Agropecuaria'), ('ganaderia', 'Ganadería'), ('venta_insumos', 'Venta de Insumos'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Actividad Comercial')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles_fotos/', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
