# Generated by Django 5.0.6 on 2025-01-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa o Pymes')),
                ('anio_fundacion', models.DateField(blank=True, null=True, verbose_name='Año de Fundación')),
                ('actividad_economica', models.CharField(blank=True, max_length=255, null=True)),
                ('preferencias_agropecuarias', models.CharField(blank=True, max_length=255, null=True)),
                ('preferencias_comerciales', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
