# Generated by Django 5.0.6 on 2025-01-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Contenido de la bibliografía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibliografía',
                'verbose_name_plural': 'Bibliografías',
                'ordering': ['-created_at'],
            },
        ),
    ]
