# Generated by Django 5.0.6 on 2025-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de YouTube'),
        ),
    ]
