# Generated by Django 5.0.6 on 2025-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_perfil_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Instagram'),
        ),
    ]
