# Generated by Django 5.0.6 on 2025-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0003_perfil_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de WhatsApp'),
        ),
    ]
