# Generated by Django 5.0.6 on 2025-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0004_perfil_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagen de Fondo'),
        ),
    ]
