# Generated by Django 5.0.6 on 2025-01-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('NOTICIAS', 'Noticias'), ('CURSOS', 'Cursos'), ('CONSEJOS', 'Consejos'), ('BLOGGER', 'Bloger'), ('PUBLICITARIO', 'Publicitario'), ('SERVICIOS_PROFESIONALES', 'Servicios Profesionales'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='estrellas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Medios.video')),
            ],
        ),
    ]
