# Generated by Django 5.0.6 on 2025-01-31 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('ganado', 'Ganado'), ('caballo', 'Caballo'), ('chancho', 'Chancho')], max_length=10)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='subastas/')),
                ('video', models.FileField(blank=True, null=True, upload_to='subastas/videos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='subastas/docs/')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='subasta.subasta')),
            ],
        ),
        migrations.CreateModel(
            name='SubastaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='subastas/images/')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='subasta.subasta')),
            ],
        ),
    ]
