# Generated by Django 5.0.6 on 2025-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subasta',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
