# Generated by Django 5.0.6 on 2025-01-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='subasta',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='subastas/docs/'),
        ),
        migrations.CreateModel(
            name='SubastaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='subastas/images/')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='subasta.subasta')),
            ],
        ),
    ]
