# Generated by Django 5.0.6 on 2025-01-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='precio_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subasta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='subastas/videos/'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='subasta.subasta'),
        ),
    ]
