# Generated by Django 5.0.6 on 2025-01-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0002_remove_subasta_imagen_subasta_document_subastaimagen'),
        ('subasta', '0002_subasta_precio_reserva_subasta_video_and_more'),
    ]

    operations = [
    ]
