# Generated by Django 5.0.6 on 2025-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='servicios',
            field=models.TextField(blank=True, help_text='Lista de servicios que brinda la finca', null=True),
        ),
        migrations.AddField(
            model_name='finca',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('turistica', 'Turística'), ('recreacional', 'Recreacional (sin fines de lucro)')], help_text='Selecciona el tipo de actividad', max_length=20, null=True),
        ),
    ]
