# Generated by Django 5.0.6 on 2025-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0002_finca_servicios_finca_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='tamaño',
            field=models.FloatField(help_text='Tamaño en metros cuadrados'),
        ),
    ]
