# Generated by Django 5.0.6 on 2025-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0004_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='animales',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de animales (ej: vacas) si es un potrero'),
        ),
    ]
