# Generated by Django 5.0.6 on 2025-02-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0005_division_animales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano', models.FloatField(help_text='Tamaño global del galpón en m²')),
                ('almacen_paja', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3)),
                ('tamano_almacen_paja', models.FloatField(blank=True, help_text='Tamaño del almacenamiento de paja en m²', null=True)),
                ('otro_producto', models.CharField(blank=True, help_text='Otro tipo de producto almacenado (opcional)', max_length=255, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galpones', to='Fincas.finca')),
            ],
        ),
        migrations.CreateModel(
            name='GalponDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animales', models.PositiveIntegerField(default=0, help_text='Cantidad de animales en la sección')),
                ('tamano', models.FloatField(help_text='Tamaño de la división en m²')),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='Fincas.galpon')),
            ],
        ),
    ]
