# Generated by Django 5.0.6 on 2025-02-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0006_galpon_galpondivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='control_animales/')),
                ('nombre', models.CharField(help_text='Nombre del Animal', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_animal', models.CharField(help_text='Tipo de Animal', max_length=50)),
                ('raza', models.CharField(help_text='Raza', max_length=100)),
                ('peso', models.FloatField(help_text='Peso (en kg)')),
                ('edad', models.FloatField(help_text='Edad (puede ser en años o meses)')),
                ('tipo_tratamiento', models.CharField(help_text='Tipo de Tratamiento', max_length=100)),
                ('nombre_medicina', models.CharField(help_text='Nombre de la Medicina', max_length=100)),
                ('cantidad', models.FloatField(help_text='Cantidad aplicada')),
                ('tipo_control', models.CharField(help_text='Tipo de Control', max_length=100)),
                ('num_arete', models.CharField(help_text='Número de Arete o de Identificación', max_length=50)),
                ('atendido_por', models.CharField(help_text='Nombre de quien atiende el animal', max_length=100)),
                ('ubicacion', models.CharField(help_text='Ubicación del animal en la finca', max_length=255)),
                ('fecha_control', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del control')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_animales', to='Fincas.finca')),
            ],
        ),
    ]
