# Generated by Django 5.0.6 on 2025-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0007_controlanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlanimal',
            name='cantidad',
            field=models.CharField(help_text='Cantidad aplicada (ej: 1 onza, 100 gramos)', max_length=50),
        ),
        migrations.AlterField(
            model_name='controlanimal',
            name='edad',
            field=models.CharField(help_text='Edad (ej: 4 meses)', max_length=50),
        ),
    ]
