# Generated by Django 5.0.6 on 2025-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0008_alter_controlanimal_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galpon',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen o foto del galpón (opcional)', null=True, upload_to='galpones/'),
        ),
    ]
