# Generated by Django 5.0.6 on 2025-02-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0009_galpon_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('lista_productos', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_transaccion', models.CharField(choices=[('gasto', 'Gasto'), ('venta', 'Venta'), ('equipo', 'Equipo'), ('inversion', 'Inversión'), ('planilla', 'Planilla'), ('servicios', 'Servicios'), ('insumos', 'Insumos')], max_length=20)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gastos/')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Fincas.finca')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profesion_estudios', models.CharField(max_length=255)),
                ('servicios_requeridos', models.TextField(blank=True, null=True)),
                ('area_designada', models.CharField(max_length=255)),
                ('contrato', models.BooleanField(default=False)),
                ('salario_por_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal/')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='Fincas.finca')),
            ],
        ),
    ]
