# Generated by Django 5.0.6 on 2025-02-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, help_text='País al que corresponde el índice', max_length=50, null=True)),
                ('main_categoria', models.CharField(choices=[('productos', 'Productos'), ('insumos', 'Insumos'), ('animales', 'Animales')], help_text='Seleccione la categoría principal.', max_length=20)),
                ('sub_categoria', models.CharField(blank=True, choices=[('carnes', 'Carnes'), ('granos', 'Granos'), ('vegetales', 'Vegetales'), ('frutas', 'Frutas'), ('lacteos', 'Lácteos')], help_text='Solo para Productos: seleccione una subcategoría.', max_length=20, null=True)),
                ('fecha', models.DateField(help_text='Fecha del índice')),
                ('nombre', models.CharField(help_text='Nombre o descripción breve del índice', max_length=100)),
                ('sube', models.CharField(choices=[('sube', 'Sube'), ('baja', 'Baja')], default='sube', help_text='Indica si el índice sube o baja', max_length=4)),
                ('antes', models.IntegerField(help_text="Valor 'Antes' (por ejemplo, 56)")),
                ('total', models.IntegerField(help_text="Valor 'Total' (por ejemplo, 80)")),
                ('precio_actual', models.DecimalField(decimal_places=2, help_text='Precio actual (por ejemplo, 100.00)', max_digits=10)),
                ('inflacion', models.DecimalField(decimal_places=2, help_text='Porcentaje de Inflación (por ejemplo, 33.00)', max_digits=5)),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa (opcional)', null=True, upload_to='indices/')),
            ],
        ),
        migrations.CreateModel(
            name='LugarRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio promedio', max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='lugares/')),
                ('url', models.URLField(blank=True, help_text='Sitio web del lugar (opcional)', null=True)),
            ],
        ),
    ]
