# Generated by Django 5.0.6 on 2025-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='fuente',
            field=models.CharField(blank=True, help_text='Fuente de la información (opcional)', max_length=255, null=True),
        ),
    ]
