# Generated by Django 5.0.6 on 2025-02-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indices', '0002_indice_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarrecomendado',
            name='precio',
            field=models.CharField(help_text='Precio promedio', max_length=50),
        ),
    ]
