# Generated by Django 5.0.6 on 2025-02-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indices', '0002_lugarrecomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='pais',
            field=models.CharField(blank=True, help_text='País al que corresponde el índice', max_length=50, null=True),
        ),
    ]
