# Generated by Django 5.0.6 on 2025-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indices', '0005_reaccionlugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaccionlugar',
            name='tipo',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡'), ('poop', '💩')], max_length=10),
        ),
    ]
