# Generated by Django 5.0.6 on 2025-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='angry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='haha_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='love_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='poop_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='sad_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foro',
            name='wow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
