# Generated by Django 5.0.6 on 2025-02-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foro', '0002_foro_angry_count_foro_haha_count_foro_like_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='angry_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='estrellas',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='haha_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='love_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='poop_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='sad_count',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='wow_count',
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('poop', 'Poop')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Foro.foro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
